name: "Open AI"
description: "Access the openai.com"
author: "Orie Steele"
inputs:
  api-key:
    description: "OpenAI api key."
    required: true
  summarize:
    description: "Input text to summarize"

outputs:
  text:
    description: "Output as text"
runs:
  using: "docker"
  image: "Dockerfile"
