name: "Open AI"
description: "Access the openai.com"
inputs:
  api-key:
    description: |
      Open AI api key.

  summarize:
    description: |
      Text to summarize

outputs:
  json:
    description: "The output in as json."
  text:
    description: "The output in as text."
runs:
  using: "node16"
  main: "dist/index.js"
