name: "Open AI"
description: "Access openai.com"
inputs:
  api-key:
    description: |
      Open AI api key.

  engine:
    description: |
      Engines describe and provide access to these models. 
      You can also customize our base models for your specific use case with fine-tuning.
      See: https://beta.openai.com/docs/engines/overview
    default: "text-davinci-002"

  prompt:
    description: |
      The prompt you would like a completion for. 
      See: https://beta.openai.com/examples.
    required: true

  temperature:
    description: |
      What sampling temperature to use. Higher values means the model will take more risks. 
      Try 0.9 for more creative applications, and 0 (argmax sampling) for ones with a well-defined answer.
      Learn more: https://beta.openai.com/docs/api-reference/completions/create#completions/temperature
    default: 0

  max_tokens:
    description: |
      The maximum number of tokens to generate in the completion.
      The token count of your prompt plus max_tokens cannot exceed the model's context length. 
      Most models have a context length of 2048 tokens (except for the newest models, which support 4096).
      Learn more: https://beta.openai.com/docs/api-reference/completions/create#completions/create-max_tokens
    default: 60

  top_p:
    description: |
      An alternative to sampling with temperature, called nucleus sampling, 
      where the model considers the results of the tokens with top_p probability mass. 
      So 0.1 means only the tokens comprising the top 10% probability mass are considered.
      We generally recommend altering this or temperature but not both.
      Learn more: https://beta.openai.com/docs/api-reference/completions/create#completions/create-top_p
    default: 1.0

  frequency_penalty:
    description: |
      Number between -2.0 and 2.0. 
      Positive values penalize new tokens based on their existing frequency in the text so far, 
      decreasing the model's likelihood to repeat the same line verbatim.
      Learn more: https://beta.openai.com/docs/api-reference/completions/create#completions/create-frequency_penalty
    default: 0.0

  presence_penalty:
    description: |
      Number between -2.0 and 2.0. 
      Positive values penalize new tokens based on whether they appear in the text so far, 
      increasing the model's likelihood to talk about new topics.
      Learn more: https://beta.openai.com/docs/api-reference/completions/create#completions/create-presence_penalty
    default: 0.0

outputs:
  json:
    description: "The output in as json."
  text:
    description: "The output in as text."
runs:
  using: "node16"
  main: "dist/index.js"
