name: CI

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    name: Checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Save
        uses: actions/cache@v3
        with:
          path: |
            ./*
          key: ${{ github.sha }}

  summarize:
    needs:
      - checkout
    runs-on: ubuntu-latest
    name: Summarize Text
    outputs:
      json: ${{ steps.read.outputs.json }}
    steps:
      - name: Cache Restore
        uses: actions/cache@v2
        id: cache-restore
        with:
          path: |
            ./*
          key: ${{ github.sha }}

      - name: Summarize Text
        uses: ./
        id: summarize
        with:
          api-key: ${{ secrets.OPENAI_API_KEY }}
          summarize: "hello world"

      - name: Review the results
        run: |-
          echo "${{ steps.summarize.outputs.text }}"
