name: CI

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    name: Checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Save
        uses: actions/cache@v3
        with:
          path: |
            ./*
          key: ${{ github.sha }}

  create-completion:
    needs:
      - checkout
    runs-on: ubuntu-latest
    name: Create Completion
    outputs:
      json: ${{ steps.completion.outputs.json }}
    steps:
      - name: Cache Restore
        uses: actions/cache@v2
        id: cache-restore
        with:
          path: |
            ./*
          key: ${{ github.sha }}

      - name: Generate a Recipe from Ingredients
        uses: ./
        id: completion
        with:
          api-key: ${{ secrets.OPENAI_API_KEY }}
          temperature: 0.3
          max_tokens: 120
          top_p: 1.0
          frequency_penalty: 0.0
          presence_penalty: 0.0
          prompt: |-
            Write a recipe based on these ingredients and instructions:

            Frito Pie

            Ingredients:
            Fritos
            Chili
            Shredded cheddar cheese
            Sweet white or red onions, diced small
            Sour cream

            Instructions:

      - name: Review the results
        run: |-
          echo "${{ steps.completion.outputs.text }}"
