name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: or13/open-ai@main
        with:
          api-key: "123-456"
          text: "hello world"

      - name: Review output
        run: |
          echo "${{ steps.selftest.outputs.text }}"
